# Generated by Django 4.2.6 on 2023-10-13 00:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0003_alter_order_items"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="total",
            field=models.CharField(default=0, max_length=200),
        ),
    ]
